m2m-relations_2/articles/urls.py
from django.urls import path

from articles.views import articles_list

urlpatterns = [
    path('', articles_list, name='articles'),
]

m2m-relations_2/website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('articles.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

m2m-relations_2/articles/models.py
from django.db import models
import datetime


class Article(models.Model):

    title = models.CharField(max_length=256, verbose_name='Название')
    text = models.TextField(verbose_name='Текст')
    published_at = models.DateTimeField(verbose_name='Дата публикации')
    image = models.ImageField(null=True, blank=True, verbose_name='Изображение')
    sections = models.ManyToManyField('Section', related_name='articles', blank=True, through='ArticleSection')
    main_section = models.ForeignKey('Section', on_delete=models.CASCADE, related_name='main_articles',
                                     blank=True, null=True)
    objects = models.Manager()

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['-id']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.published_at:
            self.published_at = datetime.datetime.now()
        super().save(*args, **kwargs)


class Section(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Раздел'
        verbose_name_plural = 'Разделы'
        ordering = ['name']

    def __str__(self):
        return self.name


class ArticleSection(models.Model):
    article = models.ForeignKey('Article', on_delete=models.CASCADE)
    section = models.ForeignKey('Section', on_delete=models.CASCADE)
    is_main = models.BooleanField(default=False)
    objects = models.Manager()

    class Meta:
        verbose_name = 'Раздел статьи'
        verbose_name_plural = 'Разделы статьи'
        unique_together = ('article', 'section')
        ordering = ['section__name']

    def __str__(self):
        return f'{self.article} - {self.section}'

    @classmethod
    def get_sorted_sections(cls, article_id):
        return cls.objects.filter(article_id=article_id).order_by('-is_main', 'section__name')

m2m-relations_2/articles/views.py
from django.shortcuts import render
from articles.models import Article


def articles_list(request):
    sort = request.GET.get('sort')
    if sort == 'date':
        articles = Article.objects.order_by('-published_at')
    elif sort == 'title':
        articles = Article.objects.order_by('title')
    else:
        articles = Article.objects.all()
    template = 'articles/news.html'
    context = {'articles': articles}
    return render(request, template, context)

m2m-relations_2/templates/articles/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
      <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <!-- Bootstrap core CSS -->
    <link href="{% static  "css/bootstrap.min.css"  %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static  "css/3-col-portfolio.css" %}" rel="stylesheet">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
      <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Будь в курсе событий</a>
      </div>
    </nav>

    <div class="container">{% block content %}{% endblock %}</div>

    <!--JavaScript at end of body for optimized loading-->
    <script type="text/javascript" src="{% static "js/bootstrap.bundle.min.js" %}"></script>
      <!-- Bootstrap core JavaScript -->
    <script src="{% static  "js/jquery.min.js" %}"></script>
  </body>
</html>

m2m-relations_2/templates/articles/news.html
{% extends "articles/base.html" %}
{% load static %}

{% block title %}Новости{% endblock %}
{% block content %}
<div class="sort-block">
    <span class="sort-item">Сортировать по:</span>
    <a class="sort-item" href="?sort=title">названию</a>
    <a class="sort-item" href="?sort=date">дате публикации</a>
</div>
<div class="row">
    {% for article in articles %}
    {% for section in article.articlesection_set.get_sorted_sections(article.id) %}
    {% if section.is_main %}
    <span class="badge badge-primary">{{ section.section.name }}</span>
    {% else %}
    <span class="badge badge-secondary">{{ section.section.name }}</span>
    {% endif %}
    {% endfor %}
    <div class="col-lg-4 col-sm-6 portfolio-item">
        <div class="card h-100">
            <a href="#"><img class="card-img-top" src="{% get_media_prefix %}{{ article.image }}" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                    <a href="#">{{ article.title }}</a>
                </h4>
                <p class="card-text">{{ article.text }}</p>
                {% for scope in article.scopes.all %}
                <span class="badge {% if scope.is_main %}badge-primary{% else %}badge-secondary{% endif %}">{{ scope.topic }}</span>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}